version: '3.0'
services:
  rasaactions:
    build: .
    container_name: "actionserver"    
    ports:
      - 5055:5055
    volumes:
      - ./:/app/actions      
    networks:
      - rasa_network    
  rasa:
    build:     
      dockerfile: Dockerfile
      context: ./rasabot
    ports:
      - 5006:5006
    volumes:
      - ./:/app
    networks:  
      - rasa_network
      - db_network
      - web_network  
    depends_on: 
      - rasaactions        
  appseed-app:
    restart: always
    env_file: .env
    build: 
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "5005:5005"
    networks:
      - db_network
      - web_network
    depends_on: 
      - rasa           
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app 
networks:
        db_network:
          driver: bridge
        web_network:
          driver: bridge 
        rasa_network:
          driver: bridge   